return {
	["find.file"] = require("actions.find.file"),
	["find.class"] = require("actions.find.class"),
	["find.symbol"] = require("actions.find.symbol"),
	["find.local_symbol"] = require("actions.find.local_symbol"),
	["find.local_text"] = require("actions.find.local_text"),
	["find.text"] = require("actions.find.text"),

	["jump.definition"] = require("actions.jump.definition"),
	["jump.implementation"] = require("actions.jump.implementation"),
	["jump.usages"] = require("actions.jump.usages"),
	["jump.prev"] = require("actions.jump.prev"),
	["jump.next"] = require("actions.jump.next"),
	["jump.recent_files"] = require("actions.jump.recent_files"),

	["edit.line_duplicate"] = require("actions.edit.line_duplicate"),
	["edit.line_delete"] = require("actions.edit.line_delete"),
	["edit.line_move_up"] = require("actions.edit.line_move_up"),
	["edit.line_move_down"] = require("actions.edit.line_move_down"),
	["edit.line_join"] = require("actions.edit.line_join"),
	["edit.line_comment"] = require("actions.edit.line_comment"),
	["edit.block_comment"] = require("actions.edit.block_comment"),
	["edit.format"] = require("actions.edit.format"),

	["completion.open"] = require("actions.completion.open"),
	["completion.open_context"] = require("actions.completion.open_context"),
	["completion.show_parameter"] = require("actions.completion.show_parameter"),
	["completion.show_documentation"] = require("actions.completion.show_documentation"),
	["completion.show_actions"] = require("actions.completion.show_actions"),

	["refactor.optiomize_imports"] = require("actions.refactor.optiomize_imports"),
	["refactor.rename"] = require("actions.refactor.rename"),
	["refactor.change_signature"] = require("actions.refactor.change_signature"),
	["refactor.extract_method"] = require("actions.refactor.extract_method"),
	["refactor.extract_variable"] = require("actions.refactor.extract_variable"),
	["refactor.extract_field"] = require("actions.refactor.extract_field"),
	["refactor.extract_constant"] = require("actions.refactor.extract_constant"),
	["refactor.inline"] = require("actions.refactor.inline"),
	["refactor.delete"] = require("actions.refactor.delete"),
	["refactor.open"] = require("actions.refactor.open"),

	["generate.surround_with"] = require("actions.generate.surround_with"),
	["generate.code"] = require("actions.generate.code"),
	["generate.override"] = require("actions.generate.override"),
	["generate.implementation"] = require("actions.generate.implementation"),

	["debug.toggle_breakpoint"] = require("actions.debug.toggle_breakpoint"),
	["debug.start_debug"] = require("actions.debug.start_debug"),
	["debug.start_run"] = require("actions.debug.start_run"),
	["debug.start_last"] = require("actions.debug.start_last"),
	["debug.step_over"] = require("actions.debug.step_over"),
	["debug.step_into"] = require("actions.debug.step_into"),
	["debug.step_out"] = require("actions.debug.step_out"),
	["debug.continue"] = require("actions.debug.continue"),
	["debug.stop"] = require("actions.debug.stop"),
	["debug.eval_expression"] = require("actions.debug.eval_expression"),

	["select.multi_next"] = require("actions.select.multi_next"),
	["select.multi_all"] = require("actions.select.multi_all"),
	["select.block"] = require("actions.select.block"),
	["select.expand_up"] = require("actions.select.expand_up"),
	["select.expand_down"] = require("actions.select.expand_down"),

	["tools.git"] = require("actions.tools.git"),
	["tools.terminal"] = require("actions.tools.terminal"),
}