name: Build and push Docker image
on:
  push:
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          DOCKER_TAG=$(echo ${{ github.ref }} | sed 's/^refs\/tags\///')
          docker build \
            -f container/base/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/nvim-base:$DOCKER_TAG \
            -t ${{ secrets.DOCKER_USERNAME }}/nvim-base:latest \
            -t nvim-base .
          docker build \
            -f container/dotnet/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/nvim-dotnet:$DOCKER_TAG \
            -t ${{ secrets.DOCKER_USERNAME }}/nvim-dotnet:latest \
            -t nvim-dotnet .
          docker build \
            -f container/latex/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/nvim-latex:$DOCKER_TAG \
            -t ${{ secrets.DOCKER_USERNAME }}/nvim-latex:latest \
            -t nvim-latex .
          docker build \
            -f container/coq/Dockerfile \
            -t ${{ secrets.DOCKER_USERNAME }}/nvim-coq:$DOCKER_TAG \
            -t ${{ secrets.DOCKER_USERNAME }}/nvim-coq:latest \
            -t nvim-coq .

      - name: Push Docker image
        run: |
          DOCKER_TAG=$(echo ${{ github.ref }} | sed 's/^refs\/tags\///')
          docker push -a ${{ secrets.DOCKER_USERNAME }}/nvim-base
          docker push -a ${{ secrets.DOCKER_USERNAME }}/nvim-dotnet
          docker push -a ${{ secrets.DOCKER_USERNAME }}/nvim-latex
          docker push -a ${{ secrets.DOCKER_USERNAME }}/nvim-coq
